apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeview.fullname" . }}
  labels:
    {{- include "kubeview.labels" . | nindent 4 }}
  {{- if .Values.serviceAnnotations }}
  annotations:
    {{- toYaml .Values.serviceAnnotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.loadBalancer.enabled }}
  type: LoadBalancer
  {{- else if .Values.nodePort.enabled }}
  type: NodePort
  {{- else if not .Values.nodePort.enabled }}
  type: ClusterIP
  {{- end }}
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
    {{- if .Values.nodePort.enabled }}
      nodePort: {{ .Values.nodePort.port | default 30000 }}
    {{- end }}
  selector:
    {{- include "kubeview.selectorLabels" . | nindent 4 }}
{{- if (and .Values.loadBalancer.enabled .Values.loadBalancer.IP) }}
  loadBalancerIP: {{ .Values.loadBalancer.IP }}
{{- end }}
