apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeview
  namespace: monitoring

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeview-role
rules:
  - apiGroups: ["extensions"]
    resources:
      - ingresses
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
      - daemonsets
      - statefulsets
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources:
      - pods
      - ingresses
      - events
      - endpoints
      - namespaces
      - nodes
      - persistentvolumes
      - persistentvolumeclaims
      - resourcequotas
      - services
    verbs: ["get", "list"]
  - nonResourceURLs: ["*"]
    verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeview
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeview-role
subjects:
  - kind: ServiceAccount
    name: kubeview
    namespace: monitoring