# ================================================================
# Default values for KubeView Helm Chart
# ================================================================

# -- Configure single namespace mode:
# `false` - Show resources in all namespaces. This is the default.
# `true` - Show resources only in namespace Kubeview is installed to.
# "string" - Only show resources in the named namespace (can be *different* from the one Kubeview is installed to).
singleNamespace: false

# -- If you want to hide certain namespaces, use a regular expression here, e.g. `kube-\|aks-`
namespaceFilter: ''

# -- Set to true to disable access to pod logs from the API and UI.
disablePodLogs: false

# -- Set to true to enable debug mode, which outputs much more information in the logs
debug: false

ingress:
  # -- Expose the app via an Ingress
  enabled: false
  # -- The domain name to use for the Ingress, required if enabled
  host: ''
  # -- To enable HTTPS, set this to reference a TLS secret (with a valid cert)
  tlsSecretName: ''
  # -- The Ingress class to use, if you have multiple ingress controllers
  className: ''
  # -- Extra Ingress annotations
  annotations: {}

loadBalancer:
  # -- Set to true to enable the LoadBalancer service type
  enabled: true
  # -- Optionally set the LoadBalancer IP address if you want to use a static IP
  IP: ''

nodePort:
  # -- Set to true to enable NodePort service type
  enabled: false
  # -- Optionally set the NodePort number, if you want to use a specific one
  port: 30000

# -- This is for the secrets for pulling an image from a private repository
imagePullSecrets: []
# -- This is to override the chart name when naming resources
nameOverride: ''
# -- This is to fully override the name of the chart & release when naming resources
fullnameOverride: ''

image:
  # -- Only change this if you've built & pushed your own image to a registry
  repository: ghcr.io/benc-uk/kubeview
  # -- This sets the pull policy for images
  pullPolicy: Always
  # -- Specify the image tag to use. If you want to use a specific version, set it here.
  tag: 'latest'

# -- For adding custom annotations to the pods
podAnnotations: {}
# -- For adding custom labels to the pods
podLabels: {}

# -- For adding custom annotations to the service
serviceAnnotations: {}

# -- Sets pod security context if you need that sort of thing
podSecurityContext: {}

# -- Sets container security context if you need to run as a specific user or group
securityContext: {}

# -- Run multiple instances of the Kubeview pod
replicaCount: 1

# -- This is for changing the resource limits and requests for the Kubeview pods
resources:
  limits:
    cpu: 50m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 64Mi

# -- If you want to schedule the pods to specific nodes, you can set node selectors here
nodeSelector: {}

# -- If you want to set specific tolerations for the pods, you can set them here
tolerations: []

# -- If you want to set specific affinity rules for the pods, you can set them here
affinity: {}
