apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeview.fullname" . }}
  namespace: {{ .Release.Namespace }}

---

{{ if .Values.limitNamespace }}
kind: Role
{{ else }}
kind: ClusterRole
{{ end }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kubeview.fullname" . }}
rules:
  - apiGroups: ["extensions"]
    resources:
      - ingresses
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
      - daemonsets
      - statefulsets
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources:
      - pods
      - configmaps
      - secrets
      - events
      - endpoints
      - namespaces
      - nodes
      - persistentvolumes
      - persistentvolumeclaims
      - resourcequotas
      - services
    verbs: ["get", "list"]
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs: ["get", "list"]
{{ if not .Values.limitNamespace }}
  - nonResourceURLs: ["*"]
    verbs: ["get", "list"]
{{ end }}

---

{{ if .Values.limitNamespace }}
kind: RoleBinding
{{ else }}
kind: ClusterRoleBinding
{{ end }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kubeview.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  {{ if .Values.limitNamespace }}
  kind: Role
  {{ else }}
  kind: ClusterRole
  {{ end }}
  name: {{ include "kubeview.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubeview.fullname" . }}
    namespace: {{ .Release.Namespace }}
