# Air configuration file for a Go project
# This file is used to configure the behavior of the Air tool, which is a live reloading tool for Go applications.
# For more information, see: https://github.com/air-verse/air

root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
bin = "./tmp/main"
cmd = "go build -o ./tmp/main -ldflags \"-X main.version=$VERSION -X 'main.buildInfo=$BUILD_INFO'\" github.com/benc-uk/kubeview/server"
delay = 1000
exclude_dir = ["tmp", "dev", "public", "bin", "docs", "deploy"]
exclude_file = []
exclude_regex = [".*_templ.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "templ"]
include_file = []
kill_delay = "0s"
log = "build-errors.log"
poll = false
poll_interval = 0
post_cmd = []
pre_cmd = []
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
silent = false
time = false

[misc]
clean_on_exit = true

[proxy]
app_port = 0
enabled = false
proxy_port = 0

[screen]
clear_on_rebuild = true
keep_scroll = true
