name: CI Build

# This is a generic CI pipeline that assumes project is to be built as a container image
# Note. CI build only builds 'latest' image, not a versioned release

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  IMAGE_REG: ghcr.io
  IMAGE_NAME: kubeview
  IMAGE_TAG: latest

permissions:
  packages: write

jobs:
  ci-build:
    name: Code Check & CI build
    runs-on: ubuntu-latest

    steps:
      # Checkout code from repo
      - name: Checkout repo
        uses: actions/checkout@v2

      # Ensures Go is configured properly
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17.2"

      # Validate code
      - name: Check code for linting and format errors
        run: make lint

      # Build image
      - name: Build the container image
        run: make image IMAGE_REPO=$GITHUB_ACTOR/$IMAGE_NAME

      # Only when pushing to default branch (e.g. master or main), then push image to registry
      - name: Push to container registry
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login $IMAGE_REG -u $GITHUB_ACTOR --password-stdin
          make push IMAGE_REPO=$GITHUB_ACTOR/$IMAGE_NAME
